### ISSUE TITLE
I am working on a similar asset for Unity utilizing LiteNetLib

### ISSUE THREAD

**Issue by miketheprogrammer** [Saishy/TinyBirdNet-Unity#1]
First let me say awesome work. 
I wanted to introduce myself. Hey im Mike. :)

The goals of my project are to create a networking library more similar to Amazons GridMate. I may also help contributing to LiteNetLib for some of the features that people have been requesting that I would also love to see.

If your down we should chat some time about the current implementations of networking that Unity and third parties have to offer, and what we see as limitations, and how we can improve networking in the unity community.

Take care and awesome work. My email is listed on my profile.

**Comment by Saishy** [comment]
Already entered in contact
