### ISSUE TITLE
SyncVars: No hook functionality?

### ISSUE THREAD

**Issue by SoftwareGuy** [Saishy/TinyBirdNet-Unity#10]
Apparently the SyncVar implementation that TinyBirdNet features does not support hooks. As the kit I'm trying to migrate to TinyBirdNet uses some of these hooks, I'm going to have to implement workarounds.

Is there any reason why hooks are not implemented or are they currently on the to-do list?

**Comment by Saishy** [comment]
Because all syncvars are properties, you can call whatever you want inside
the set method.

**Comment by SoftwareGuy** [comment]
Could you please provide an example code snippet?
