### ISSUE TITLE
Why can I only use 32 TinyNetSyncVar?

### ISSUE THREAD

**Issue by love451990105** [Saishy/TinyBirdNet-Unity#3]
Why can I only use 32 TinyNetSyncVar?

**Comment by love451990105** [comment]
Because it take more time to traverse all the 【TinyNetSyncVar】 in 【TinyNetBehaviour】 At Awake，When there are more than 32 【TinyNetSyncVar】 ?

**Comment by Saishy** [comment]
Hi.

Yes I had to limit syncvars to the smallest possible number that was still usable since they are heavy and bloated.

Although you can change that limit or just implement ur own serialization/deserialization method!
