### ISSUE TITLE
Highest Means?

### ISSUE THREAD

**Issue by love451990105** [Saishy/TinyBirdNet-Unity#4]
![image](https://user-images.githubusercontent.com/43029566/45261285-8e623c80-b431-11e8-9076-8bb42547863b.png)

I don't understand the meaning of "Highest". Do you mean the new value is written below this "Highest"?

**Comment by love451990105** [comment]
![image](https://user-images.githubusercontent.com/43029566/45261313-1e07eb00-b432-11e8-954d-0d1b754d9053.png)

Because the following method haunt me.

**Comment by Saishy** [comment]
It means that is the highest id used by system messages.
So if you want to create your own messages they should have an ID higher
than that.

**Comment by Saishy** [comment]
Oh that is a debug function.
I guess I should make a way to have it own messages with readable names?
Not sure how at moment tho.
