### ISSUE TITLE
The idea of server switching？

### ISSUE THREAD

**Issue by love451990105** [Saishy/TinyBirdNet-Unity#5]
I am very grateful to you for your help.😭

Because I am not familiar with the Internet, I would like to ask you what you think about server switching?

Server switching means 

when a server disconnects, it allows a client player to become a server.

**Comment by Saishy** [comment]
I think it's good?

**Comment by love451990105** [comment]
hhhh, no, I want to ask if you can realize the Server switching under your current framework.

I noticed that in your code, the client is divided into two types, one is ListenServer and the other is a normal client.

Will this make the Server switching impossible? Or what advantage does it do than to separate client types?

**Comment by Saishy** [comment]
It's certainly doable, tho I'm focusing on a pitch release of my game for
this end of year and I won't be back until around February...
