### ISSUE TITLE
Sorry to bother you again...

### ISSUE THREAD

**Issue by love451990105** [Saishy/TinyBirdNet-Unity#6]
![_20180911150736](https://user-images.githubusercontent.com/43029566/45343868-b047f480-b5d4-11e8-8c78-da27e878b7b6.png)
![image](https://user-images.githubusercontent.com/43029566/45344178-93f88780-b5d5-11e8-9fce-f5269ebb7592.png)

Why not use FixedUpdate directly just like Update did?

**Comment by Saishy** [comment]
Hi, no worry!

So about that is because WaitForFixedUpdate will always run after all
physics calculation, making sure the game frame will be sent with the
latest data to clients.

https://docs.unity3d.com/Manual/ExecutionOrder.html

**Comment by love451990105** [comment]
👍😘thank
