### ISSUE TITLE
Is this project... abandoned?

### ISSUE THREAD

**Issue by SoftwareGuy** [Saishy/TinyBirdNet-Unity#8]
Hi there,

Just wondering if the current version of TinyBirdNet-Unity is stable or if it's got any bugs/gotchas that need to be addressed? I also wanted to know if the project is still alive and kicking, because I really do like the idea of a UNET-like HLAPI that will plug directly into LiteNetLib rather than going through and having to manually write adapters, wrappers and all that painful things. However, the last commit date was a little concerning, so I thought I'd open a issue ticket and ask.

Cheers!

**Comment by Saishy** [comment]
Hi,

I didn't receive any bugs complaints so far.

The commit date is because I'm reworking a lot of the internal stuff to add
things like a cycle buffer and server reconciliation.

Also I was polishing my game's pitch, and the game will use TinyBirdNet, so
no worries it will be abandoned.

**Comment by SoftwareGuy** [comment]
Could you go into more detail regarding the cycle buffer, and how your server reconciliation would work?  

Would the latter be enabled by default or have to manually be enabled per object that requires the server to rewind position data? Are you also using a server authoritative system for security?

I currently use another UNET-like framework for my shooter game's networking, but I will be giving this library a test. Since the shooter game framework I use uses mainly RPCs and some other components that can be replaced with scripts/other ways of doing the component's job, I see a fairly smooth change-over.

I personally believe if you make a solid and battle-tested framework it will succeed very well - the new Unity networking stack feels really sloppy/half-rushed, and I wouldn't use it in production until it was proven stable.
